--- 
  - name: Install docker and python
    yum:
      update_cache: yes
      name:
        - docker-ce
        - python3
        - python3-pip
        - python3-setuptools
        - iputils
      state: present
    tags: packages
    become: true

  - name: Install packages
    yum: 
      update_cache: yes
      name:
        - ca-certificates
        - curl
        - python-virtualenv
      state: latest 
    tags: packages
    become: true
  
  - name: Install Docker Module for Python
    pip:
      name: docker
      executable: pip3
    tags: pip_docker
    become: true
